# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99b0be0997aa009b0f40416627093fc9aa121dade171bf0d2696a1843d44c0efc07af3350bbb696d4481e430badf93c9bb8c539e92dba0dcd1fa80c807633062

test:
  secret_key_base: 3f2c2b4e3cb6946690c623ef96530853d2bad82743103e12659ac9b74ee89a62ba61b64a343a3349729c24c9f2c4ce51c5dc70eef85e458745f6c5b679f69007

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
